apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/cb0/counter
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
          - source 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-storage