apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-deployment
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: docker.io/enricovalastro/counter_app_server:latest
        ports:
        - containerPort: 3500
        volumeMounts:
        - mountPath: "/etc/counter"
          name: task-pv-storage
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: counter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter
  type: NodePort
  ports:
  - protocol: TCP
    port: 3500
    targetPort: 3500
    nodePort: 30020