apiVersion: v1
kind: PersistentVolume
metadata:
  name: ekuiper-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/cb0/kuiper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
          - source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ekuiper-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage