apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: nfs-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.244.2.65"
    path: "/pvc" # "pvc" folder must exist in "/exports" directory of NFS server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nfs-data

